### ISSUE TITLE
FlightRadar24 feeder out of date

### ISSUE THREAD

**Issue by lukerv4** [Thom-x/docker-fr24feed-piaware-dump1090#105] opened 2023-01-19 15:03 UTC
## Specifications

  - Image hash or version: 1.18
  - Platform:  Docker
  - Subsystem: Unraid 

## Expected Behavior

FlightRadar 24 feeder is updated to latest version

## Actual Behavior

FlightRadar 24 feeder is out of date as of January 19th 2023 with version 1.0.25-3 and FlightRadar will stop supporting this version after Feb 28, 2023. Email Received from FlighRadar regarding the issue

## Steps to Reproduce the Problem
 ![chrome_2023-01-19_09-57-33](https://user-images.githubusercontent.com/32318163/213476857-645a913e-cbeb-4bcf-b88a-993de3b4ac70.png)

**Comment by that-one-tom** [comment] 2023-01-19 16:25
Hi, this seems to be a duplicate of #104, so you might want to follow the conversation over there 🙂

**Closed** 2023-01-19 16:26 UTC
